### ISSUE TITLE
Feat/ 검색 페이지 마무리

### ISSUE THREAD

**Issue by devBuzz142** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#119]
## 기능 요청

- 검색페이지 부족한 기능 보완

### 🎨 구현할 내용

- 버튼 누를 시 검색 submit
- 검색어 없을 경우 전체 출력
- css - > 가운데 정렬 및 카드 크기
- 스크롤 css?

### 예상 구현 시간
2시간

### 시급한 정도

🚨

**Comment by Steadystudy** [comment]
UserInfoItem에 총 코인 수가 없습니다

**Comment by Steadystudy** [comment]
@devBuzz142 ItemWrapper 안 UserInfoItem에 key 값을 넣어야 될 거 같군요
![스크린샷 2022-06-21 오후 2 19 10](https://user-images.githubusercontent.com/76620786/174721814-690741b8-0d8b-4879-a399-990cbc6952f8.png)
