### ISSUE TITLE
Feat/ BottomBar 컴포넌트 구현

### ISSUE THREAD

**Issue by blacktoast** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#13]
### 📌 설명

매인 피드 바텀바 컴포넌트 구현

### 🎨 구현할 내용
- [x] Icon base 컴포넌트 구현

### 시급한 정도

🚨

**Comment by blacktoast** [comment]
route 연결은 이후 작업 할 예정이라서 지우고 pr할게요

**Comment by MayOwall** [comment]
제가 pr을 issue와 연동시켜 놓지 않아 자동으로 close 되지 않았네요 ㅜㅠ
이번만 수동으로 close 하고 다음부터는 연동 시켜놓도록 하겠습니다.
