### ISSUE TITLE
Feat/ 메인 피드 헤더 만들기

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#16]
### 📌 설명

메인 피드 헤더 구현

### 🎨 구현할 내용
- [] 메인 피드 헤더

### 시급한 정도

🚨

**Comment by Steadystudy** [comment]
제가 만들도록 하겠습니다

**Comment by Steadystudy** [comment]
만들다 보니 Avatar, Icon component를 사용해야 되고 이미지를 받아와야하기 때문에 footer와 maincard 먼저 머지된 후 만들겠습니다

**Comment by Steadystudy** [comment]
#16/Feat/Header로 브랜치 만들어서 만들도록 하겠습니다

**Comment by MayOwall** [comment]
상기님 해당 컴포넌트는 hotfix되어야 할 만큼 긴급하진 않은것 같아요..!!
혹시 보통으로 바꾸시는건 어떠신가용...ㅎㅎ
