### ISSUE TITLE
Feat/ 메인 피드 페이지 구현

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#18]
### 📌 설명

PageTemplate, mainCard 컴포넌트를 활용하여 메인 피드 페이지 만들기

![image](https://user-images.githubusercontent.com/97934878/173544027-c2d8e2ee-a308-4228-aad1-fff6d26f44df.png)

### 🎨 구현할 내용
- [ ] 메인 피드 페이지

### 시급한 정도

🏃🏻

**Comment by MayOwall** [comment]
혹시 이건 제가 해 봐도 될까요??
상기님 Header PR merge 하시면
확인 후에 바로 진행 해 볼께요 ☺️

**Comment by Steadystudy** [comment]
넵 알겠습니다~!

**Comment by devBuzz142** [comment]
이슈의 구현할 내용에 구현사항에 대한 체크리스트를 좀 더 상세하게 적고 들어가는 것은 어떠신가요?
헤더 컴포넌트를 구현할 때, 헤더/배너에 대한 구분이 덜 된채로 들어가서 팀원 간 다소 혼동이 있었는데, 이슈에 미리 명시하고 명시된 것을 위주로 구현하면 소통이 원활할 것 같아서요.
@Steadystudy @MayOwall
