### ISSUE TITLE
Refactor/ Icon, BottomBar

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#21]
### 이슈
페이지템플릿에 페이지마다 필요한 iconList를 직접 BottomBar 컴포넌트에 전달하는 과정이 직관적이지 않습니다. 

### 설명
page만 전달하고 BottomBar에서 직접 icon을 생성하는 방향으로 리팩토링하기로 하였습니다.
그 과정에서 아이콘 또한 상위 컴포넌트로부터 src를 받아 렌더링하는 것보다, 아이콘타입을 입력받으면 Icon컴포넌트는 아이콘타입에 따라 맞는 아이콘 src를 불러, 렌더링하는 방향으로 리팩토링 하기로 하였습니다.

### 수정 요청

- [x]  eslint
    - react-default-required : 0
- [x]  BottomBar 이름은 확정
- Icon
    - [x]  assets/icons 폴더 만들기
    - [x]  assets/icons/index.js를 통해 export default IconLlist
    - [x]  Icon 컴포넌트 리팩토링 : 받는 props 수정 (src 대신 icon과 type)
    - [ ]  Icon 스토리북 생성 → 라디오
    - [ ]  BottomBar 컴포넌트 리팩토링 : props 수정
    - [ ] props 디폴트값 넣기

    page 받아서, page마다 서로 다른 iconList 생성, iconList를 여러 아이콘에 전달
    
    - [ ]  BottomBar 스토리북 생성

 - [x] 따봉 아이콘은 페이지가 변경해도 그대로 일테니 props로 넣지 않고 고정

**Comment by MayOwall** [comment]
확인하였습니다!

이건 제가 하도록 하겠습니다.
메인 페이지를 구현하기 전에 이거 먼저 하겠습니다~

**Comment by devBuzz142** [comment]
@MayOwall 이거 혹시 저녁에 같이 하실 수 있을까요? 안그래도 바텀바, 아이콘 리팩토링 하는거 제안하기도 했고 해보고 싶었는데요

**Comment by MayOwall** [comment]
네 확인했습니다 저녁 먹고 디코에서 이야기 나눠요~

**Comment by blacktoast** [comment]
아 이게 props로 안 넣어주고 컴포넌트안에서 그냥 아이콘를 넣으면 스토리북에서 안보여요

만약 한다면 디폴트 값으로 해야 할 것 같습니다
