### ISSUE TITLE
Refactor/ Header 새로운 디자인으로 수정

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#28]
### 📌 설명
![스크린샷 2022-06-11 오후 10 02 55](https://user-images.githubusercontent.com/76620786/173301698-58a182b3-b0ae-44f6-abe1-9e00aa24c9fa.png)

<img width="414" alt="스크린샷 2022-06-13 오후 4 27 33" src="https://user-images.githubusercontent.com/76620786/173301669-ea0e9d0f-4d8f-48ff-b410-8068dd128311.png">

위 디자인에서 아래 디자인으로 변경
### 🎨 구현할 내용
- [] notification 아이콘 추가
- logo 중앙으로 옮기기
- notification이 있을 때 아이콘에 빨간 뱃지 달기

### 시급한 정도

🏃🏻

**Comment by blacktoast** [comment]
제가 어제 이야기 한대로 지금 해더도 조금 수정을 하고 있습니다.
뱃지 부분도 그럼 제가 할게요

**Comment by Steadystudy** [comment]
넵 감사함다~!
