### ISSUE TITLE
Feat/ Rank 페이지 구현

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#29]
### 📌 설명

랭킹 페이지 구현
![스크린샷 2022-06-14 오후 2 34 40](https://user-images.githubusercontent.com/76620786/173500896-34c9e945-ec5c-41ee-9a81-f2a812e536fe.png)

`pages/RankPage` 폴더 안에서 만들 생각입니다
브랜치명은 `\#29/Feat/RankPage`로 하겠습니다

### 🎨 구현할 내용
- [] page template 사용
- [] Tab (base component로 만들어 사용)
![스크린샷 2022-06-14 오후 2 36 42](https://user-images.githubusercontent.com/76620786/173501159-46840660-b455-4f0a-850a-85de5a501fef.png)
- [] BaseContentContainer (base component로 만들어 사용)
- [] FirstRankInfo
![스크린샷 2022-06-14 오후 2 37 55](https://user-images.githubusercontent.com/76620786/173501298-ddd097cd-105b-4e39-a24f-6d6b25db4f48.png)
- [] userInfoItem (base component로 만들어 사용)
![스크린샷 2022-06-14 오후 2 40 29](https://user-images.githubusercontent.com/76620786/173501609-b5b9248f-2f7f-42b6-9d3d-0bcb586ef758.png)

### 시급한 정도

🏃🏻

**Comment by Steadystudy** [comment]
제가 하겠습니다~

**Comment by devBuzz142** [comment]
1. 순위는 뱃지가 아닌 것 같습니다. 그냥 다른 이름으로 해도 될 것 같아요

2. 랭커가 바로 와닿지 않는데 랭크리스트, 랭크아이쳄은 어떤가요?

3. 랭킹페이지 구현 들어가신다는거 같이 있을 때 얘기가 된건가요? 슬랙이나 디코에서 못 들었어가지구요

**Comment by devBuzz142** [comment]
1. 랭크 리스트 -> 랭크 아이템 (랭크 / 랭커 인포) 어떠신가요

**Comment by Steadystudy** [comment]
오 좋은 것 같슴다~!
