### ISSUE TITLE
Feat/ UserInfoItem 컴포넌트 구현

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#36]
### 📌 설명

ranking page와 다른 곳에서도 사용가능한 userInfoItem 컴포넌트 구현
-랭킹 페이지
![스크린샷 2022-06-14 오후 2 43 10](https://user-images.githubusercontent.com/76620786/173501925-13a37e44-284a-4d54-85f6-29a5fefa34bc.png)
- 검색페이지
![스크린샷 2022-06-14 오후 2 43 22](https://user-images.githubusercontent.com/76620786/173501955-bddb3fde-b622-430d-8134-6eaaf860ef23.png)

### 🎨 구현할 내용
- [] 랭크 및 아바타 이미지를 넣을 container
- [] 사용자 이름 넣을 container
- [] 코인 수, 따봉 수를 넣을 container

### 시급한 정도

🏃🏻

**Comment by Steadystudy** [comment]
제가 만들겠습니다~

**Comment by devBuzz142** [comment]
@Steadystudy 
[] 랭크 및 아바타 이미지를 넣을 container
[] 사용자 이름 넣을 container
[] 코인 수, 따봉 수를 넣을 container
작은 단위라서 Wrapper로 가는 것은 어떠신가요?
