### ISSUE TITLE
Refactor/ storybook-react-router

### ISSUE THREAD

**Issue by devBuzz142** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#45]
## 기능 요청

storybook-react-router 라이브러리를 사용하여 스토리북에서의 라우팅 관련 문제 해결

### 📌 설명

<Route> <Link>와 같은 react-router-dom 컴포넌트는 <Router>안에서 사용되어야 합니다.
그러나 스토리북은 <App>안에서 돌아가는 것이 아니기 때문에 에러가 발생합니다.

이를 수정하기 위해 현재 임시방편으로, 라우팅을 사용하는 컴포넌트는 해당 스토리북 파일에서 <Router>로 따로 감싸주고 있습니다.

storybook-react-router 라이브러리를 사용하여 해결하는 방법도 있기에 일단 이슈만 파 놨습니다.

참조
https://www.npmjs.com/package/storybook-react-router
https://stackoverflow.com/questions/58909666/storybook-w-react-router-you-should-not-use-link-outside-router

### 🎨 구현할 내용
- [ ] storybook-react-router 설치
- [ ] 스토리북에 decoration 추가

### 시급한 정도

🐢
적용 안해도 좋습니다.

**Comment by Steadystudy** [comment]
적용 안했을 때는 storybook 만들 때마다 Router로 감싸주면 되나요?
