### ISSUE TITLE
Feat/ MainCard props 변수명(commentCount) 수정 요청

### ISSUE THREAD

**Issue by MayOwall** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#50]
### 📌 설명

MainCard의 props중 하나인 commenCount의 변수명 수정 요청

<br>

### 🎨 구현할 내용

- [ ] MainCard의 props중 하나인 commenCount의 변수명을 commentCount로 수정해야 할 것 같습니다.

현재 props 상황
![image](https://user-images.githubusercontent.com/97934878/173768450-294ba98c-ca85-4f5b-962f-3823fd6174af.png)

<br>

### 시급한 정도

🐢 천천히

**Comment by blacktoast** [comment]
아 이건 기존 pr에서 제가 수정해서 날릴게요

**Comment by Steadystudy** [comment]
아하! 확인하셨군요
