### ISSUE TITLE
Feat/ CardDetail Api 연동작업

### ISSUE THREAD

**Issue by blacktoast** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#60]
### 📌 설명
기존 따봉 디테일 카드 페이지에서 api 연동 작업
+ 기존 CardDetail 리팩토링

### 🎨 구현할 내용

- [] 다이나믹 라우팅으로 가져온 값으로 api 호출
- [] Api를 통해 받은 데이터로 CardDetail 렌더링
- [] BaseCardContainer 을 사용해서 CardDetail 리팩토링
### 예상 구현 시간
4시간 예상

### 시급한 정도

🏃🏻 보통

**Comment by devBuzz142** [comment]
4시간..!
