### ISSUE TITLE
Feat/ MainFeedPage API 연동 작업

### ISSUE THREAD

**Issue by MayOwall** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#72]
### 📌 설명

메인페이지에 api를 붙여보자!

<br>

### 🎨 구현할 내용

메인페이지가 api 데이터를 통해 렌더링 할 수 있도록 로직을 구현할 계획입니다.

<br>

### 예상 구현 시간

하루...정도.... 더 길어질 수 있습니다.
api 문서를 이해해야 해서 시간이 좀 더 걸릴 수 있습니다 흑흑
너무 늦어진다면 돌을 던져 주세요..💨

<br>

### 시급한 정도

🏃🏻 보통

<br>

**Comment by devBuzz142** [comment]
@MayOwall 
api 문서 당장 이해가 안가시면 남는 사람 잡고 같이 작업해요! 그게 더 효율나고 개발기한이 얼마 안 남아서 좋을거예요
