### ISSUE TITLE
Feat/ 칭찬하기 페이지 구현

### ISSUE THREAD

**Issue by Steadystudy** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#80]
### 📌 설명

칭찬하기 페이지 구현
<img width="290" alt="스크린샷 2022-06-18 오후 6 09 16" src="https://user-images.githubusercontent.com/76620786/174430960-51aba989-8e8c-4d6b-87dd-eab14df7052f.png">

### 🎨 구현할 내용

- 칭찬 대상자 모달 만들기 (receiver) => 만약 여러명일 경우?
- 칭찬 사유 textarea or contentEditable div? (title.content)
- 사진 업로드 (image)
- 라벨 리스트 (labelItems)
- 칭찬하기 버튼 클릭시 내용 post하기

자세한 내용 : 1차 프로젝트 문서/ 기록/ 칭찬하기 페이지
### 예상 구현 시간
하루? (더 걸릴듯 합니다)

### 시급한 정도

🏃🏻

**Comment by devBuzz142** [comment]
@Steadystudy 제가 시작하겠습니다
