### ISSUE TITLE
Feat/ Context API를 통한 User 정보 전역상태관리

### ISSUE THREAD

**Issue by woojerry** [prgrms-fe-devcourse/FEDC2_TTaBong_Dali#88]
### 📌 설명

-Context API를 통한 전역상태관리

### 🎨 구현할 내용

-AuthRoute, ProtectedRoute 생성  ([참고](https://dev.to/nilanth/how-to-create-public-and-private-routes-using-react-router-72m))
- auth 상태 전역으로 관리 및 유지

### 시급한 정도

🏃🏻 보통

**Comment by Steadystudy** [comment]
public, protected route를 분리해서 만들어도 좋을 것 같아요
